[project]
name = "adobe-hack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.0.0",
    "numpy>=1.21.0,<2.0.0",
    "pymupdf==1.26.3",
    "scikit-learn>=1.0.0,<2.0.0",
]
