[project]
name = "problem1a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.2",
    "pymupdf>=1.26.3",
    "torch>=2.7.1",
    "transformers>=4.54.0",
    "pytest>=8.0.0",
    "psutil>=7.0.0",
]
